package gui;

import donkeycardgameclient.GamplayThread;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.PrintStream;
import java.net.Socket;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import server.Card;
import server.DGame;
import server.Player;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Marko
 */
public class GameWindow extends javax.swing.JFrame {

    Socket soket = null;
    PrintStream izlazniTokKaServeru = null;
    String playerName = null;
    LinkedList<Player> playerList = new LinkedList<>();
    Player player1 = null;
    Player player2 = null;
    Player player3 = null;
    Card[] myCards = new Card[5];

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
    }

    public GameWindow(Socket soketParam, String playerName) {
        try {
            initComponents();
            labelWaitForPlayers.setVisible(false);
            this.playerName = playerName;
            namePlayer.setText(playerName);
            soket = soketParam;
            izlazniTokKaServeru = new PrintStream(soket.getOutputStream());
            new GamplayThread(soket, this).start();

        } catch (IOException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // metode za komunikaciju sa GamplayThread klasom
    public void changePlayerStatus(LinkedList<Player> list) {
        playerList = list;
        if (playerList.size() < 4) {
            labelWaitForPlayers.setVisible(true);
        } else {
            labelWaitForPlayers.setVisible(false);
        }
        for (int i = 0; i < playerList.size(); i++) {
            if(playerList.get(i) == null) {
                continue;
            }
            boolean exists = false;
            if(playerList.get(i).getPlayerName().equals(playerName)) {
                exists = true;
                continue;
            }
            if(playerList.get(i).getPlayerName().equals(player1.getPlayerName())) {
                player1 = playerList.get(i);
                exists = true;
                continue;
            }
            if(playerList.get(i).getPlayerName().equals(player2.getPlayerName())) {
                player2 = playerList.get(i);
                exists = true;
                continue;
            }
            if(playerList.get(i).getPlayerName().equals(player3.getPlayerName())) {
                player3 = playerList.get(i);
                exists = true;
                continue;
            }
            if(exists == false) {
                if(player1 == null) {
                    player1 = playerList.get(i);
                    continue;
                }
                if(player2 == null) {
                    player2 = playerList.get(i);
                    continue;
                }
                if(player3 == null) {
                    player3 = playerList.get(i);
                    continue;
                }
            }
            
        }
        
    }

    public void getMyCards(Card[] cards) {
        myCards = cards;
    }

    public void receveCard(Card card) {
        for (int i = 0; i < myCards.length; i++) {
            if (myCards[i] == null) {
                myCards[i] = card;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JLabel();
        donkey1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        donkey3 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        donkey2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCard1 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        btnCard4 = new javax.swing.JButton();
        btnCard5 = new javax.swing.JButton();
        btnCard2 = new javax.swing.JButton();
        namePlayer = new javax.swing.JLabel();
        donkeyPlayer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelWaitForPlayers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Donkey game");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/index.jpg")));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name1.setText("Name player 1");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        donkey1.setText("Donkey 1");
        getContentPane().add(donkey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 34, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5 cards 2 of clubs players 1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 67, -1, -1));

        donkey3.setText("Donkey 3");
        getContentPane().add(donkey3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 61, -1, -1));

        name3.setText("Name player 3");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 33, -1, -1));

        donkey2.setText("Donkey 2");
        getContentPane().add(donkey2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 61, -1, -1));

        name2.setText("Name player 2");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 33, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5 cards back players 2,3.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5 cards back players 2,3.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 95, -1, -1));
        getContentPane().add(btnCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 242, 58, 94));

        btnCard3.setText("jButton1");
        getContentPane().add(btnCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 242, -1, 94));

        btnCard4.setText("jButton1");
        getContentPane().add(btnCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 242, -1, 94));

        btnCard5.setText("jButton1");
        getContentPane().add(btnCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 242, -1, 94));

        btnCard2.setText("jButton1");
        getContentPane().add(btnCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 242, -1, 94));

        namePlayer.setText("Username");
        getContentPane().add(namePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 354, -1, -1));

        donkeyPlayer.setText("Donkey player");
        getContentPane().add(donkeyPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 388, -1, -1));

        jButton1.setText("PUT DOWN YOUR CARDS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 184, 208, -1));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Droped cars");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 94, -1));

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Droped cars");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 73, -1));

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Droped cars");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 16, 120, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Time to play");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 77, 115, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("30");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 113, -1, -1));

        labelWaitForPlayers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelWaitForPlayers.setForeground(new java.awt.Color(204, 0, 0));
        labelWaitForPlayers.setText("Waiting for all players");
        getContentPane().add(labelWaitForPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 95, -1, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        try {
//            Image img = ImageIO.read(getClass().getResource("resources/1.1.jpg"));
//            ImageIcon icon = new ImageIcon(img);
//            Image image = icon.getImage();
//            // reduce by 50%
//            image = image.getScaledInstance(image.getWidth(null) / 2, image.getHeight(null) / 2, Image.SCALE_SMOOTH);
//            icon.setImage(image);
//
//            btnCard1.setIcon(icon);
//
//        } catch (IOException ex) {
//            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnCard4;
    private javax.swing.JButton btnCard5;
    private javax.swing.JLabel donkey1;
    private javax.swing.JLabel donkey2;
    private javax.swing.JLabel donkey3;
    private javax.swing.JLabel donkeyPlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelWaitForPlayers;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel namePlayer;
    // End of variables declaration//GEN-END:variables
}
